### ISSUE TITLE
Cannot find pretrained model

### ISSUE THREAD

**Issue by ckzbullbullet** [OLeoghain/image_caption-lstm#2]
Hi, Thanks for the codes. However, when I checked the link that downloads the vocab and pretrained-model, I can only find the vocab file. 

Could you please share me some pretrained model for decoder?

Thanks!

**Comment by OLeoghain** [comment]
Sorry for the delay in reply. I have updated the link with the pretrained models.

**Comment by OLeoghain** [comment]
https://drive.google.com/drive/folders/1QW8RsfB11z7Qc7yNYhjBi4eFI5E13cG0
decoder and encoder
